[IMP] - في القرض أصبح هناك مشكل في تجاوز شهر ،سداد كامل المبلغ - تغيير منيو السنة المالية بالسنوات ، ومصطلح السنة المالية ب السنة - عند القيام باشاء سنة جديدة 1439 يقوم بإنشاء فترات للعام الحالي يعني لا يأخذ بعين العتبار تاريخ بداية ونهاية ألسنة . - إضافة زر إغلاق وإعادة فتح الفترة - يجب أن لا ينشء فترات إلا عن طريق زر إنشاء فترات شهرية : حذف إمكانية إنشاء وتعديل فترة - رغم أني اخترت الشهر الحالي في إنشاء مسير إفرادي أو جماعي غير أنه تظهر : لا يمكن انشاء مسير لشهر في المستقبل - في مسير جماعي عند ضغط على زر إحتسب هناك مشكل : ValueError: Expected singleton: hr.payslip.worked_days(59, 58, 57, 56, 55, 62) - في مسير إفرادي عند إختيار موظف هناك مشكل : ValueError: Expected singleton: hr.payslip.worked_days(59, 58, 57, 56, 55, 62) -- الفترة يجب أن تكون required في مسير جماعي ويمكن تغييرها إلا في حالة مسودة . - الفترة يجب أن تكون required في الفروقات ويمكن تغييرها إلا في حالة طلب . - الفترة يجب أن تكون required في الحسميات ويمكن تغييرها إلا في حالة طلب . - تغيير مسمى الحاله من طلب إلى إعداد في الفروقات والحسميات - إسناد المزايا المالية لا تعمل بعد إختيار الموظفين AttributeError: 'hr.bonus' object has no attribute 'month_from'